### ISSUE TITLE
Segmentation error

### ISSUE THREAD

**Issue by edrevo** [eclipse/openj9#10367]
Java -version output
--------------------
```
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (build 1.8.0_265-b01)
Eclipse OpenJ9 VM (build openj9-0.21.0, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20200728_727 (JIT enabled, AOT enabled)
OpenJ9   - 34cf4c075
OMR      - 113e54219
JCL      - c82ff0c20f based on jdk8u265-b01)
```

Summary of problem
------------------

This happened compiling Scala code through SBT. My JAVA_OPTS are `-Xshareclasses:cacheDir=/home/ximo/.openj9cache,nonfatal,name=sbt -Xmx10G`

```
Unhandled exception
Type=Segmentation error vmState=0x00040000
J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
Handler1=00007F8DCA7E1FC0 Handler2=00007F8DCA0D1A60 InaccessibleAddress=0000000000000018
RDI=000000000018C320 RSI=000000000000001C RAX=000000000017EB00 RBX=00007F8DC41116D0
RCX=000000000018C2E0 RDX=0000000000000000 R8=000000000000001F R9=000000000018BD00
R10=0000000000000008 R11=00007F8D6D67FE58 R12=00007F8D6D6803D6 R13=00007F8D6D5C62E6
R14=0000000001D81A00 R15=0000000006883090
RIP=00007F8DCA7DD31C GS=0000 FS=0000 RSP=00007F8D6C8B5160
EFlags=0000000000010283 CS=0033 RBP=00000000000003E0 ERR=0000000000000004
TRAPNO=000000000000000E OLDMASK=0000000000000000 CR2=0000000000000018
xmm0 000000004c6dd859 (f: 1282267264.000000, d: 6.335242e-315)
xmm1 6e6f6974704f2f61 (f: 1884237696.000000, d: 9.083672e+223)
xmm2 ffffffffffffffff (f: 4294967296.000000, d: -nan)
xmm3 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm4 43e0000000000000 (f: 0.000000, d: 9.223372e+18)
xmm5 000000003e1d3279 (f: 1042100864.000000, d: 5.148662e-315)
xmm6 000000004c6dd859 (f: 1282267264.000000, d: 6.335242e-315)
xmm7 0000000000000004 (f: 4.000000, d: 1.976263e-323)
xmm8 0001740073000077 (f: 1929379968.000000, d: 2.020829e-309)
xmm9 2c333d736c726d73 (f: 1819438464.000000, d: 9.007565e-96)
xmm10 2c333d73393f323d (f: 960442944.000000, d: 9.007564e-96)
xmm11 ca62c1d6ca62c1d6 (f: 3395469824.000000, d: -2.193092e+50)
xmm12 416dd18000000000 (f: 0.000000, d: 1.563341e+07)
xmm13 000000004b6c189a (f: 1265375360.000000, d: 6.251785e-315)
xmm14 000000003e800000 (f: 1048576000.000000, d: 5.180654e-315)
xmm15 000000004b118648 (f: 1259439744.000000, d: 6.222459e-315)
Module=/usr/lib/jvm/adoptopenjdk-8-openj9-amd64/jre/lib/amd64/compressedrefs/libj9vm29.so
Module_base_address=00007F8DCA74E000
Target=2_90_20200728_727 (Linux 4.19.84-microsoft-standard)
CPU=amd64 (8 logical CPUs) (0x4ae77f000 RAM)
----------- Stack Backtrace -----------
(0x00007F8DCA7DD31C [libj9vm29.so+0x8f31c])
(0x00007F8DC3613505 [libjclse29.so+0x1d505])
Java_java_lang_J9VMInternals_getStackTrace+0x30 (0x00007F8DC36103B0 [libjclse29.so+0x1a3b0])
(0x00007F8DCA886464 [libj9vm29.so+0x138464])
(0x00007F8DCA883B77 [libj9vm29.so+0x135b77])
(0x00007F8DCA77041A [libj9vm29.so+0x2241a])
```

Diagnostic files
----------------

https://1drv.ms/u/s!AvHYjMzLfKM5g8gb4-R-1kP5kH_9XQ?e=ixb26h

**Comment by keithc-ca** [comment]
It seems you're running within WSL. Does the problem go away if you use `-Xshareclasses:none`?
If so, it would seem you've encountered https://github.com/Microsoft/WSL/issues/1927.
By the way, WSL is not a supported platform for OpenJ9.

**Comment by edrevo** [comment]
Thanks for the quick update. It definitely looks like that WSL issue. It's a pitty WSL isn't a supported platform. OpenJ9 gives me a 10s bootup improvement for SBT!

Thanks for the awesome work with OpenJ9!

**Comment by keithc-ca** [comment]
That's definitely a big improvement.

It's surprising (and disappointing) to me that Microsoft has left that bug unattended for so long.

**Comment by edrevo** [comment]
According to https://github.com/microsoft/WSL/issues/1927#issuecomment-672922537, the issue is fixed in WSL2 (which is what I was using), so the culprit should be something else. Either way, since WSL isn't a supported platform I'm out of luck I guess.

**Comment by keithc-ca** [comment]
I started to check whether WSL 2 fixes the problem, but it conflicts badly with my use of VirtualBox.

Please double-check the version you are using with `wsl -l -v`. Even if you have WSL 2 installed, each package can be independently configured for WSL version 1 or version 2.

**Comment by edrevo** [comment]
```
PS C:\Users\HI_ximo> wsl -l -v
  NAME                   STATE           VERSION
* Ubuntu-20.04           Running         2
  docker-desktop-data    Running         2
  docker-desktop         Running         2
```

**Comment by keithc-ca** [comment]
The shared class cache implementation in OpenJ9 makes use of `fcntl`. If disabling the cache makes the problem go away, then that suggests to me that microsoft/WSL#1927 is not fixed (at least for the file system you're using; the claim is that 'it's a real ext4 filesystem' perhaps doesn't apply if you're working in a mounted NTFS file system).

**Comment by pshipton** [comment]
If the problem is related to file locks, you can try with the `nonpersistent` shared cache option, where file locks are not used. The shared cache won't persist over a reboot, but otherwise it works the same.

https://www.eclipse.org/openj9/docs/xshareclasses/#nonpersistent
