### ISSUE TITLE
Class loading on Java 15 is failing while working on HotSpot

### ISSUE THREAD

**Issue by mbarbero** [eclipse/openj9#11308]
I'm trying to use `org.xerial:sqlite-jdbc` with AdoptOpenJDK 15 (with OpenJ9 JVM). Unfortunately, the NativeDB class cannot be loaded while it works well with HotSpot/Java 15 and many other version combinations. See the following tests on macOS 11.0.1 (20B29):

```bash
❯ /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/java -cp "target/*:target/lib/*" App 
AdoptOpenJDK 1.8.0_275 (AdoptOpenJDK)
Mac OS X 10.16 (x86_64)
JDBC Driver Name: SQLite JDBC

❯ /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home/bin/java -cp "target/*:target/lib/*" App
AdoptOpenJDK 11.0.9.1 (AdoptOpenJDK)
Mac OS X 10.16 (x86_64)
JDBC Driver Name: SQLite JDBC

❯ /Library/Java/JavaVirtualMachines/adoptopenjdk-15.jdk/Contents/Home/bin/java -cp "target/*:target/lib/*" App
AdoptOpenJDK 15 (AdoptOpenJDK)
Mac OS X 10.16 (x86_64)
JDBC Driver Name: SQLite JDBC

❯ /Library/Java/JavaVirtualMachines/adoptopenjdk-8-openj9.jdk/Contents/Home/bin/java -cp "target/*:target/lib/*" App 
Eclipse OpenJ9 1.8.0_275 (Eclipse OpenJ9)
Mac OS X 10.16 (x86_64)
JDBC Driver Name: SQLite JDBC

❯ /Library/Java/JavaVirtualMachines/adoptopenjdk-11-openj9.jdk/Contents/Home/bin/java -cp "target/*:target/lib/*" App
AdoptOpenJDK 11.0.9 (Eclipse OpenJ9)
Mac OS X 10.16 (x86_64)
JDBC Driver Name: SQLite JDBC

❯ /Library/Java/JavaVirtualMachines/adoptopenjdk-15-openj9.jdk/Contents/Home/bin/java -cp "target/*:target/lib/*" App
AdoptOpenJDK 15.0.1 (Eclipse OpenJ9)
Mac OS X 10.16 (x86_64)
Exception in thread "main" java.lang.NoClassDefFoundError: org.sqlite.core.NativeDB
        at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
        at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:383)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:227)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:169)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:1787)
        at java.base/java.lang.System.load(System.java:581)
        at org.sqlite.SQLiteJDBCLoader.loadNativeLibrary(SQLiteJDBCLoader.java:277)
        at org.sqlite.SQLiteJDBCLoader.extractAndLoadLibraryFile(SQLiteJDBCLoader.java:256)
        at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:344)
        at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:67)
        at org.sqlite.core.NativeDB.load(NativeDB.java:63)
        at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:235)
        at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:61)
        at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28)
        at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:21)
        at org.sqlite.JDBC.createConnection(JDBC.java:115)
        at org.sqlite.JDBC.connect(JDBC.java:90)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
        at App.main(App.java:10)
Caused by: java.lang.ClassNotFoundException: org.sqlite.core.NativeDB
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1104)
        ... 20 more
```

Please find below the code used for the above test (to be put in a maven project):

`src/main/java/App.java`:
```java
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.SQLException;

public class App {
  public static void main(String[] args) throws SQLException {
    System.out.println(System.getProperty("java.vendor") + " " + System.getProperty("java.version") + " (" + System.getProperty("java.vm.vendor") + ")");
    System.out.println(System.getProperty("os.name") + " " + System.getProperty("os.version") + " (" + System.getProperty("os.arch") + ")");
    try (Connection conn = DriverManager.getConnection("jdbc:sqlite::memory:")) {
      DatabaseMetaData meta = conn.getMetaData();
      System.out.println("JDBC Driver Name: " + meta.getDriverName());
    }
  }
}
```

`pom.xm`:
```xml
<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>sqlite</groupId>
  <artifactId>mac-test</artifactId>
  <version>1.0-SNAPSHOT</version>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.xerial</groupId>
      <artifactId>sqlite-jdbc</artifactId>
      <version>3.32.3.2</version>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.8.1</version>
      </plugin>
      <plugin>
        <artifactId>maven-dependency-plugin</artifactId>
        <version>3.1.2</version>
        <executions>
          <execution>
            <phase>package</phase>
            <goals>
              <goal>copy-dependencies</goal>
            </goals>
            <configuration>
              <outputDirectory>${project.build.directory}/lib</outputDirectory>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
```

Compiled with:

```
❯ mvn -V clean verify                                                                 
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /Users/mbarbero/bin/apache-maven/latest
Java version: 15, vendor: AdoptOpenJDK, runtime: /Library/Java/JavaVirtualMachines/adoptopenjdk-15.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.16", arch: "x86_64", family: "mac"
[INFO] Scanning for projects...
[INFO] 
[INFO] --------------------------< sqlite:mac-test >---------------------------
[INFO] Building mac-test 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[...]
```

Detail about the failing version:

```
❯ /Library/Java/JavaVirtualMachines/adoptopenjdk-15-openj9.jdk/Contents/Home/bin/java -version                       
openjdk version "15.0.1" 2020-10-20
OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.1+9)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.23.0, JRE 15 Mac OS X amd64-64-Bit Compressed References 20201024_81 (JIT enabled, AOT enabled)
OpenJ9   - 0394ef754
OMR      - 582366ae5
JCL      - ad583de3b5 based on jdk-15.0.1+9)
```

Am I correct assuming that OpenJ9 should behave as Hotspot here?

**Comment by JasonFengJ9** [comment]
This is related to `jdk.internal.loader.NativeLibraries.load`, I will look at it a bit later.

**Comment by JasonFengJ9** [comment]
```
java -showversion -cp "target/*:target/lib/*" App
openjdk version "15.0.1-internal" 2020-10-20
OpenJDK Runtime Environment (build 15.0.1-internal+0-adhoc.fengjcaibmcom.openj9-openjdk-jdk15)
Eclipse OpenJ9 VM (build moduleread-6a074cce56, JRE 15 Mac OS X amd64-64-Bit Compressed References 20201127_000000 (JIT enabled, AOT enabled)
OpenJ9   - 6a074cce56
OMR      - 1f46e75cf
JCL      - d3b60198f1 based on jdk-15.0.1+9)
Eclipse OpenJ9 15.0.1-internal (Eclipse OpenJ9)
Mac OS X 10.16 (x86_64)
JDBC Driver Name: SQLite JDBC
```
@mbarbero could you share the command line option to reproduce the `ClassNotFoundException`?

**Comment by mbarbero** [comment]
I've created git repo (https://github.com/mbarbero/openj9-sqlite-11308) with the example from my intial comment. See in the [README the command line + the output](https://github.com/mbarbero/openj9-sqlite-11308#eclipse-openj9-vm-adoptopenjdk-build-openj9-0230-jre-15-mac-os-x-amd64-64-bit-compressed-references-20201024_81-jit-enabled-aot-enabled ) resulting in a fail

**Comment by JasonFengJ9** [comment]
Thanks, the failure has been reproduced with JDK15 0.23 release build, but it passes with latest nightly build [1]. It appears the issue has been resolved.

[1] https://github.com/AdoptOpenJDK/openjdk15-binaries/releases/download/jdk15u-2020-12-02-15-06/OpenJDK15U-jdk_x64_mac_openj9_2020-12-02-15-06.tar.gz

**Comment by mbarbero** [comment]
Thanks. I cannot test the linked archive. System throws me a 

> “jdk-15.0.1+9” is damaged and can’t be opened. You should move it to the Trash.

But I trust you and the team ;) Thanks for investigating, I guess this one can be closed then.

**Comment by JasonFengJ9** [comment]
> “jdk-15.0.1+9” is damaged and can’t be opened. You should move it to the Trash.

This happens when downloading it with a browser, `wget` can workaround it.

**Comment by pshipton** [comment]
Closing since it's working on the latest nightly builds.

**Comment by mbarbero** [comment]
Thanks everyone.

FYI, I just tried with latest release from Homebrew (see below, note the 20201130_124 instead of 20201024_81) and it's still failing.

```
openjdk version "15.0.1" 2020-10-20
OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.1+9)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.23.0, JRE 15 Mac OS X amd64-64-Bit Compressed References 20201130_124 (JIT enabled, AOT enabled)
OpenJ9   - 0394ef754
OMR      - 582366ae5
JCL      - ad583de3b5 based on jdk-15.0.1+9)
```

However, it works with build from comment https://github.com/eclipse/openj9/issues/11308#issuecomment-737496087, when `curl`'ing the file as suggested instead of using the browser to download it.

**Comment by JasonFengJ9** [comment]
Thanks the updates and the effort to help us troubleshooting.
Homebrew installs latest JDK15 release build, i.e., `openj9-0.23.0` which indeed fails in my test as well. Though it was built around `20201130_124`, the code splitting from main development stream happened much earlier and only selected fixes went into this release stream afterwards. It appears there is a fix or change in head stream but not in `0.23` release.
`0.24` release is coming soon which should pass this test.

**Comment by pshipton** [comment]
There was a Mac rebuild to fix a JRE Homebrew installer problem which explains `20201130_124` https://github.com/AdoptOpenJDK/TSC/issues/188

**Comment by pshipton** [comment]
The milestone 1 build for the 0.24 release is expected next week.

**Comment by pshipton** [comment]
The milestone 1 build will be announced in the OpenJ9 slack #announce channel. https://openj9.slack.com/archives/C01C8PL6319
