### ISSUE TITLE
Debug cmdLineTests on MacOS

### ISSUE THREAD

**Issue by pdbain-ibm** [eclipse/openj9#3321]
Further to 
https://github.com/eclipse/openj9/issues/3154#issue-367004249

> in cmdLineTests dir:
(Sanity: TOTAL: 81 EXECUTED: 81 PASSED: 2 FAILED: 79 SKIPPED: 0)
(Extended: TOTAL: 83 EXECUTED: 83 PASSED: 0 FAILED: 83 SKIPPED: 0)
Most cmdLineTests fail with " Darwin is not a supported OS platform"
Some variants of cmdLineTester_GCRegressionTests - fail with JVMJ9VM007E Command-line option unrecognised: -Xgcpolicy:metronome - @pdbain-ibm can you look at this?
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

Run and debug these tests.

**Comment by pdbain-ibm** [comment]
Need to set `BUILD_LIST=functional/cmdLineTests,functional/cmdline_options_testresources,functional/cmdline_options_tester`.  The last item is required to build `cmdlinetester.jar`.

```
export SPEC=osx_x86-64_cmprssptrs
export JAVA_BIN=/Users/pdbain/vm/openj9-openjdk-jdk11/build/macosx-x86_64-normal-server-release/images/jdk/bin/
export JDK_VERSION=11 
export JDK_IMPL=openj9 
export BUILD_LIST=functional/cmdLineTests,functional/cmdline_options_testresources,functional/cmdline_options_tester
make -f run_configure.mk 
make compile
make JVM_OPTIONS=-Xcompressedrefs _all
```

The shared memory tests may fail because they set `-Xscmx5M`, which is larger than the default setting setting of `kern.sysv.shmmax` to 4 MB on some MacOS systems. To fix, create `/etc/sysctl.conf` containing:
```
kern.sysv.shmmax=8388608
kern.sysv.shmmin: 1
kern.sysv.shmmni: 32
kern.sysv.shmseg: 8
kern.sysv.shmall: 1024
```
and reboot.

**Comment by pdbain-ibm** [comment]
Test results:
```
FAILED test targets:
	cmdLineTester_SCURLClassLoaderNPTests_0
	cmdLineTester_SCURLClassLoaderNPTests_1
	cmdLineTest_sigxfszHandlingTest_0
	cmdLineTester_callsitedbgddrext_openj9_0
	cmdLineTest_gpTest_0
	testSCCMLTests2_0
	testSCCMLTests2_1
	testSCCMLTests3_0
	testSCCMLTests3_1
	testSCCMLTests4_0
	testSCCMLTests4_1
	testSCCMLTests5_0
	testSCCMLTests5_1
	testSCCMLTests6_0
	testSCCMLTests6_1
	testSCCMLSnapshot_0
	testSCCMLSnapshot_1
	testSCCMLTests1_openj9_0
	testSCCMLTests1_openj9_1
	cmdLineTester_verbosetest_0
	cmdLineTester_verbosetest_1
	cmdLineTester_verbosetest_2
	cmdLineTester_verbosetest_3
	cmdLineTester_verbosetest_4
	cmdLineTester_verbosetest_5
	cmdLineTester_verbosetest_6
	cmdLineTester_classesdbgddrext_0
	cmdLineTester_classesdbgddrext_1
	cmdLineTester_modularityddrtests_0
	cmdLineTester_modularityddrtests_1
	cmdLineTester_loopReduction_0
	cmdLineTester_vmRuntimeState_0
	cmdLineTester_XcheckJNI_0
	cmdLineTester_LazyClassLoading_0
	cmdLineTester_jvmtitests_debug_0
	cmdLineTester_jvmtitests_debug_1
	cmdLineTester_jvmtitests_debug_2
	cmdLineTester_jvmtitests_debug_3
	cmdLineTester_jvmtitests_debug_4
	cmdLineTester_jvmtitests_debug_5
	cmdLineTester_jvmtitests_debug_6
	cmdLineTester_jvmtitests_debug_7
	cmdLineTester_jvmtitests_debug_8
	cmdLineTester_jvmtitests_debug_9
	cmdLineTester_jvmtitests_debug_10
	cmdLineTester_jvmtitests_debug_11
	cmdLineTester_shrcdbgddrext_0
	cmdLineTester_shrcdbgddrext_1
	cmdLineTester_shrcdbgddrext_2
```
The `cmdLineTester_GCRegressionTests` mentioned in 
https://github.com/eclipse/openj9/issues/3154#issue-367004249 all passed.

**Comment by pdbain-ibm** [comment]
- cmdLineTester_SCURLClassLoaderNPTests_* are failing due to insufficient shared memory (try 32M instead of 8).
- cmdLineTest_sigxfszHandlingTest_0: `java" -Xcompressedrefs -cp "/Users/pdbain/macprojects/openj9test/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/functional/cmdline_options_testresources/cmdlinetestresources.jar" -XX:+HandleSIGXFSZ j9vm.test.sigxfsz.SignalXfszTest test.txt` fails due to `>> Failure condition was found: [Output match: File is written successfully]`.  `-Xrs` also failed. Signal handling issue?
- cmdLineTester_callsitedbgddrext_openj9_0: `/Users/pdbain/vm/openj9-openjdk-jdk11/build/macosx-x86_64-normal-server-release/images/jdk/bin//../bin/jdmpview -core j9core.dmp`: the dump file is missing. I ran the tests manually and they worked.
- cmdLineTest_gpTest_0: Exception in thread "main" java.lang.UnsatisfiedLinkError: gptest (Not found in java.library.path).  May be related to 
https://github.com/eclipse/openj9/issues/3292
- testSCCMLTests2_0: `java -cp /Users/pdbain/macprojects/openj9test/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/functional/VM_Test/VM_Test.jar -Xshareclasses:name=ShareClassesCMLTests,utilities com.ibm.j9.sharedCacheAPI.tests.SharedUtilsTest` `Error: Could not find or load main class com.ibm.j9.sharedCacheAPI.tests.SharedUtilsTest`.  Other testSCCMLTests fail with shmmax overflow.
- cmdLineTester_verbosetest_*: FileNotFoundException: /Users/pdbain/macprojects/openj9test/jvmtest/functional/JIT_Test/testng.xml.  Looks like a test bug, since there is a `testng.xml` in `/Users/pdbain/macprojects/openj9test//openjdk-tests/functional/JIT_Test`.  Note the spurious `jvmtest/` in the path.
- cmdLineTester_classesdbgddrext_0: dump file is missing, or exists and cannot be written.  Maybe a race condition?
- cmdLineTester_loopReduction_0: Could not find or load main class jit.test.loopReduction.Main
- cmdLineTester_vmRuntimeState_0: Agent library vmruntimestateagent29 could not be opened (dlopen(libvmruntimestateagent29.dylib, 1): image not found).  Also looks like 
https://github.com/eclipse/openj9/issues/3292
- cmdLineTester_XcheckJNI_0: Exception in thread "main" java.lang.UnsatisfiedLinkError: j9ben (Not found in java.library.path). Ibid.
- cmdLineTester_LazyClassLoading_0: java.lang.UnsatisfiedLinkError: j9lazyClassLoad (Not found in java.library.path). Ibid.

Console output: [transcript.zip](https://github.com/eclipse/openj9/files/2487896/transcript.zip)

**Comment by pdbain-ibm** [comment]
I copied the libraries from `build/macosx-x86_64-normal-server-release/vm/lib*.dylib` to  `build/macosx-x86_64-normal-server-release/images/jdk/bin//../../native-test-libs`.
Test `cmdLineTest_gpTest_0` hangs Testing: abort. It creates a process which does not respond to signals and must be `kill -9`-ed.

**Comment by DanHeidinga** [comment]
> Signal handling issue?

That should be fixed in the latest OMR level.

**Comment by pdbain-ibm** [comment]
How recent?

**Comment by DanHeidinga** [comment]
It's this commit - https://github.com/eclipse/openj9-omr/commit/3c0ec910da58070f0e7a9d49e7606d77fb4843e4

I think the OMR level promoted this morning.

**Comment by pdbain-ibm** [comment]
- cmdLineTester_verbosetest_0: same issue on Linux X86.
- cmdLineTester_XcheckJNI_0: java.lang.UnsatisfiedLinkError: j9ben (Not found in java.library.path)

**Comment by pdbain-ibm** [comment]
Retested with the aforementioned version of OMR:
```
openjdk version "11-internal" 2018-09-25
OpenJDK Runtime Environment (build 11-internal+0-adhoc.pdbain.openj9-openjdk-jdk11)
Eclipse OpenJ9 VM (build master-8d06ec3e, JRE 11 Mac OS X amd64-64-Bit Compressed References 20181017_000000 (JIT enabled, AOT enabled)
OpenJ9   - 8d06ec3e
OMR      - 3c0ec910
JCL      - 4f9e2ba5c4 based on jdk-11+28)
```
The abort test still hangs.  Running manually (after copying the necessary files to `build/macosx-x86_64-normal-server-release/images/native-test-libs`:
```
$ export LD_LIBRARY_PATH=/Users/pdbain/vm/openj9-openjdk-jdk11/build/macosx-x86_64-normal-server-release/images/jdk/bin//../../native-test-libs/:/Users/pdbain/vm/openj9-openjdk-jdk11/build/macosx-x86_64-normal-server-release/images/jdk/bin//../lib/compressedrefs:/Users/pdbain/vm/openj9-openjdk-jdk11/build/macosx-x86_64-normal-server-release/images/jdk/bin//j9vm
pdbain-mac-pdbain:598$ "/Users/pdbain/vm/openj9-openjdk-jdk11/build/macosx-x86_64-normal-server-release/images/jdk/bin//java" -Xcompressedrefs -Xdump:system:none -cp "/Users/pdbain/macprojects/openj9test/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/functional/cmdline_options_testresources/cmdlinetestresources.jar" VMBench.GPTests.GPTest   abort
JVMDUMP039I Processing dump event "abort", detail "" at 2018/10/17 12:49:14 - please wait.
JVMDUMP032I JVM requested Java dump using '/Users/pdbain/vm/openj9-openjdk-jdk11/build/macosx-x86_64-normal-server-release/images/jdk/bin//javacore.20181017.124914.10041.0001.txt' in response to an event
```
... and it hangs and ignores further signals.  The process required `kill -9` to stop it.

**Comment by pdbain-ibm** [comment]
Many of the failing MacOS cmdline tests also fail on LinuxX86.  Running the same suite on the latter:
```
FAILED test targets:
        cmdLineTester_callsitedbgddrext_openj9_0
        cmdLineTester_classesdbgddrext_1
        cmdLineTest_gpTest_0
        cmdLineTester_jvmtitests_hcr_OSRG_nongold_2
        cmdLineTester_jvmtitests_hcr_OSRG_nongold_3
        cmdLineTester_jvmtitests_hcr_OSRG_nongold_4
        cmdLineTester_decompilationTests_nongold_2
        cmdLineTester_decompilationTests_nongold_3
        cmdLineTester_jvmtitests_1
        cmdLineTester_jvmtitests_2
        cmdLineTester_jvmtitests_5
        cmdLineTester_jvmtitests_7
        cmdLineTester_jvmtitests_8
        cmdLineTester_jvmtitests_hcr_4
        cmdLineTester_jvmtitests_hcr_7
        cmdLineTester_jvmtitests_hcr_8
        cmdLineTester_jvmtitests_hcr_10
        cmdLineTester_jvmtitests_debug_3
        cmdLineTester_jvmtitests_debug_5
        cmdLineTester_jvmtitests_debug_7
        cmdLineTester_jvmtitests_debug_8
        cmdLineTester_jvmtitests_debug_9
        cmdLineTester_jvmtitests_debug_11
        cmdLineTester_decompilationTests_1
        cmdLineTester_LazyClassLoading_0
        cmdLineTester_loopReduction_0
        cmdLineTester_modularityddrtests_1
        testSCCMLTests2_1
        testSCCMLTests1_openj9_1
        ShareClassesCMLOpenJ9_1
        cmdLineTester_shrcdbgddrext_1
        cmdLineTester_verbosetest_0
        cmdLineTester_verbosetest_3
        cmdLineTester_verbosetest_5
        cmdLineTester_verbosetest_6
        cmdLineTester_vmRuntimeState_0
        cmdLineTester_XcheckJNI_0
```

Tests which are failing on MacOS only are:
> cmdLineTest_sigxfszHandlingTest_0
> cmdLineTester_SCURLClassLoaderNPTests_0
> cmdLineTester_SCURLClassLoaderNPTests_1
> cmdLineTester_classesdbgddrext_0
> cmdLineTester_jvmtitests_debug_0
> cmdLineTester_jvmtitests_debug_1
> cmdLineTester_jvmtitests_debug_10
> cmdLineTester_jvmtitests_debug_2
> cmdLineTester_jvmtitests_debug_4
> cmdLineTester_jvmtitests_debug_6
> cmdLineTester_modularityddrtests_0
> cmdLineTester_shrcdbgddrext_0
> cmdLineTester_shrcdbgddrext_2
> cmdLineTester_verbosetest_1
> cmdLineTester_verbosetest_2
> cmdLineTester_verbosetest_4
> testSCCMLSnapshot_0
> testSCCMLSnapshot_1
> testSCCMLTests1_openj9_0
> testSCCMLTests2_0
> testSCCMLTests3_0
> testSCCMLTests3_1
> testSCCMLTests4_0
> testSCCMLTests4_1
> testSCCMLTests5_0
> testSCCMLTests5_1
> testSCCMLTests6_0
> testSCCMLTests6_1

The `SCC` test failure are likely due to shmmax being too small.

**Comment by pdbain-ibm** [comment]
The new OMR didn't fix the `HandleSIGXFSZ` issue:
```
---SUMMARY OF FAILED TESTS---
-XX:+HandleSIGXFSZ
-XX:-HandleSIGXFSZ -XX:+HandleSIGXFSZ
 -Xrs
-XX:+HandleSIGXFSZ -Xrs
```

**Comment by pdbain-ibm** [comment]
Bug in the JIT_Tests:
`JVMJ9VM007E Command-line option unrecognised: -Xcompressedrefs-cp`
Fixing with https://github.com/eclipse/openj9/pull/3332

**Comment by pdbain-ibm** [comment]
`cmdLineTests/classesdbgddrext` failing due to https://github.com/eclipse/openj9/issues/3343 (MacOS specific).

**Comment by pdbain-ibm** [comment]
shared classes tests fixed by setting 

- kern.sysv.shmmax: 33554432
- kern.sysv.shmall: 8192

 https://github.com/eclipse/openj9/issues/3346.

**Comment by pdbain-ibm** [comment]
- URLClassLoaderTests: all passed
- jvmtitests: failed due to "Agent library jvmtitest could not be opened", 
https://github.com/eclipse/openj9/issues/3321
- modularityddrtests: failed due to missing dump file: issue 
https://github.com/eclipse/openj9/issues/3343
- shareClassTests/SCCMLTests: ibid
- shrcdbgddrext: fails with error `The variable "SHARECLASSESOPTION" does not exist; original string used to construct the variable name was "SHARECLASSESOPTION"`
- verbosetest: failed ` -verbose:dynload,sizes,stack,debug`

**Comment by pdbain-ibm** [comment]
- Issue https://github.com/eclipse/openj9/issues/3378 for `verbosetest` failures.
- `shrcdbgddrext` failed on Linux for other reasons.

**Comment by pdbain-ibm** [comment]
https://github.com/eclipse/openj9/issues/3378 is now working.

Note that the JDK configuration & GC policy generally need to be specified via `JVM_OPTIONS` .  Failing to do so will cause the test harness to run unsupported variants.

**Comment by pdbain-ibm** [comment]
DDR tests failing due to https://github.com/eclipse/openj9/issues/3444.

**Comment by pdbain-ibm** [comment]
Opened 
https://github.com/eclipse/openj9/issues/3445 for signal handling issue.

**Comment by pdbain-ibm** [comment]
@dmitripivkine is metronome supported on MacOS, and do we document same?

**Comment by dmitripivkine** [comment]
-Xgcpolicy:metronome supported at Linux x86 and AIX only at the moment. It might be enabled on other platforms if they can support high-resolution clock.

**Comment by llxia** [comment]
>-Xgcpolicy:metronome supported at Linux x86 and AIX only at the moment. It might be enabled on other platforms if they can support high-resolution clock.

In this case, we need to update the corresponding mode and osx value pairs in https://github.com/eclipse/openj9/blob/master/test/TestConfig/resources/ottawa.csv

For example, mode351 (-Xgcpolicy:metronome -Xcompressedrefs) should not run onosx_x86-64_cmprssptrs.

I will create a separate issue for this.

**Comment by smlambert** [comment]
Yes, that's on me, as I originally instructed to copy the xLinux settings in the csv file, and we can refine from there.

**Comment by llxia** [comment]
No problem. I will fix this in #3508 :)

**Comment by babsingh** [comment]
> The abort test still hangs ... and it hangs and ignores further signals. The process required kill -9 to stop it.

**Testing: abort** no longer hangs on OSX. https://github.com/eclipse/openj9/pull/3603 seems to have fixed the hang: [Sanity - JDK11 - osx_x86-64_cmprssptrs](https://ci.eclipse.org/openj9/job/PullRequest-Sanity-JDK11-osx_x86-64_cmprssptrs-OpenJ9/33/consoleFull). **Testing: abort** still fails; the new failure is related to not setting `DYLD_LIBRARY_PATH` on OSX (https://github.com/eclipse/openj9/issues/3686).

fyi - @pdbain-ibm @DanHeidinga

**Comment by babsingh** [comment]
Related PRs:
- [PLTEST failure on OSX JDK1](https://github.com/eclipse/openj9/issues/3685)
- [Test code/infrastruture should use DYLD_LIBRARY_PATH on MacOSX](https://github.com/eclipse/openj9/issues/3686)

**Comment by babsingh** [comment]
**Summary of failing tests with JDK8 OSX:**
1. [libpathTestRtf and libpathTestRtfChild hang on OSX [JDK8/JDK11]](https://github.com/eclipse/openj9/issues/3787)
2. [gpTest suite failures on OSX with JDK8](https://github.com/eclipse/openj9/issues/3789)
3. [OSX JDK8 testSCCMLTests1 suite failures](https://github.com/eclipse/openj9/issues/3790)
4. [MacOS: sigxfszHandlingTests fail](https://github.com/eclipse/openj9/issues/3342): Updated for JDK8 OSX.
5. [GCCheck failures with JDK8 on OSX](https://github.com/eclipse/openj9/issues/3791)
6. [JDK8 OSX unrecognised option -Xgcpolicy:metronome](https://github.com/eclipse/openj9/issues/3792)
7. [JDK8 OSX Test failures: Initialization error for library j9gc29(2)](https://github.com/eclipse/openj9/issues/3795)
8. [JDK8 OSX reattachAfterExit test fails](https://github.com/eclipse/openj9/issues/3794)

**Comment by babsingh** [comment]
https://github.com/eclipse/openj9/projects/7 is also used for tracking the remaining Mac issues. This issue is redundant. @pdbain-ibm should we close this?

**Comment by pdbain-ibm** [comment]
Yes, closing.
