### ISSUE TITLE
-Xgc:concurrentScavenge not working on Windows 64bits - OpenJDK 8u192-b12

### ISSUE THREAD

**Issue by GerardoNevarez** [eclipse/openj9#3451]
Hi there,

I tried enabling the new `-Xgc:concurrentScavenge` flag on a Windows 64 OpenJDK 8 build,. but fails with the following error:

```
C:\Java\jdk8u192-b12-j9\bin>java -Xgc:concurrentScavenge -version
JVMJ9GC040E Unknown option: concurrentScavenge
JVMJ9VM015W Initialization error for library j9gc29(2): Failed to initialize; unable to parse command line
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

Wonder if this is supported on Windows x64, if not, would it be supported in a future OpenJ9 release?  Can this be a build problem? (the flag is accepted on Linux x64)

Some more details on the AdoptOpenJDK build I used:
```
C:\Java\jdk8u192-b12-j9\bin>java -version
openjdk version "1.8.0_192"
OpenJDK Runtime Environment (build 1.8.0_192-b12)
Eclipse OpenJ9 VM (build openj9-0.11.0, JRE 1.8.0 Windows 10 amd64-64-Bit Compressed References 20181019_105 (JIT enabled, AOT enabled)
OpenJ9   - 090ff9dc
OMR      - ea548a66
JCL      - 51609250b5 based on jdk8u192-b12)
```

FYI, my target is to run Eclipse 2018-09 on it, the previous relese works reasonably OK, even without the unreleased SCC OSGi plugin.

**Comment by pshipton** [comment]
Seems it was only enabled for linux_x86, which doesn't match the documentation.
https://github.com/eclipse/openj9-docs/issues/99
@0dvictor @andrewcraik

**Comment by andrewcraik** [comment]
Yup looks like it was missed @0dvictor can you get the makefile change sorted?

**Comment by 0dvictor** [comment]
I have an impression that Concurrent Scavenge is not yet supported on Windows. @amicic could you confirm?

**Comment by amicic** [comment]
Correct, not enabled on Windows. I was under impression it was intentional, because during the recent development, I'm not aware of any tests being done with CS on Windows.

**Comment by andrewcraik** [comment]
Ok we should get a test build going to see what, if anything, needs fixing on windows and revise the docs. @pshipton FYI

**Comment by pshipton** [comment]
Doc issue is https://github.com/eclipse/openj9-docs/issues/126

**Comment by pshipton** [comment]
The docs have now been updated. Keeping this issue open as a reminder to enable Windows for the next release. I've added it to the 0.12.0 milestone.

**Comment by SueChaplain** [comment]
@pshipton - can we also have the doc:externals label added so that we have a reminder to add it back to the docs please?

**Comment by DanHeidinga** [comment]
@andrewcraik  @dmitripivkine Is this still on track to be enabled on windows for the `0.12.0` release?

**Comment by andrewcraik** [comment]
I know that @0dvictor had fixed a couple of windows compile problems and was going to try running some builds - @0dvictor and @dmitripivkine status?

**Comment by 0dvictor** [comment]
Though I fixed the GC compile issues on Windows, unfortunately it doesn't seem being in a working state. Going through JIT's implementation related to concurrent scavenge, it seems complete. I don't see any OS specific code. Given the uncertainty of the underlaying failures and my limited resources, I don't have a timeline for enabling the support.

**Comment by dmitripivkine** [comment]
I am aware about one minor issue in GC related with slow GC threads initialization on startup for Windows. As a result if test ends during first CS cycle -Xcheck memory discover unreleased memory block.
@amicic Anything else?

**Comment by amicic** [comment]
There might be some  problems with startup with late/slow GC threads (which are possibly more related to being ran on a virtual instance rather than running on Windows). But I have not investigated this enough to tell exactly what the problem is.

In general, for the most part GC functionality is same for all platforms, except minor deviations at startup.

**Comment by amicic** [comment]
I did more investigation on GC side, and there is one (startup) problem to address (actually affects all plaforms, but for some reason causes real failures only on Win, rather than just a slow start on othes). I'm hoping to fix this within a week or so. 
as it stands now 0.12 with these dates is a possibility from my side, unless I uncover more problems.

**Comment by amicic** [comment]
My startup fixes (https://github.com/eclipse/omr/pull/3233) are in. In my internal personal testing, there were still failures, but all of them seemed to be with -Xjit. @0dvictor, I think you should do another round of investigation - I'm available to help.
